export let cards = [
  {
    name: "Spider-Man",
    attack: 3,
    hp: 2,
    cost: 2,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/01/29/81/96/01298196.png",
  },
  {
    name: "Iron Man",
    attack: 4,
    hp: 4,
    cost: 4,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/67/f1/88/f9/67f188f9.png",
  },
  {
    name: "Wolverine",
    attack: 3,
    hp: 4,
    cost: 3,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/2a/07/fc/12/2a07fc12.png",
  },
  {
    name: "Thor",
    attack: 4,
    hp: 5,
    cost: 3,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/0e/b0/4f/68/0eb04f68.png",
  },
  {
    name: "Hulk",
    attack: 6,
    hp: 6,
    cost: 5,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/b7/64/9b/fe/b7649bfe.png",
  },
  {
    name: "Luke Cage",
    attack: 2,
    hp: 1,
    cost: 1,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/20/98/0e/bb/20980ebb.png",
  },
  {
    name: "Nick Fury",
    attack: 1,
    hp: 1,
    cost: 1,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/af/24/09/32/af240932.png",
  },
  {
    name: "Gambit",
    attack: 2,
    hp: 2,
    cost: 2,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/40/ce/25/d1/40ce25d1.png",
  },
  {
    name: "Hawkeye",
    attack: 2,
    hp: 2,
    cost: 1,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/f8/1d/48/81/f81d4881.png",
  },
  {
    name: "Silver Surfer",
    attack: 7,
    hp: 5,
    cost: 5,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/cc/92/b5/fc/cc92b5fc.png",
  },
  {
    name: "Blade",
    attack: 3,
    hp: 2,
    cost: 2,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/b8/92/ad/5b/b892ad5b.png",
  },
  {
    name: "Nightcrawler",
    attack: 3,
    hp: 2,
    cost: 2,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/f7/b6/89/30/f7b68930.png",
  },
  {
    name: "Doctor Strange",
    attack: 3,
    hp: 4,
    cost: 4,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/31/40/8d/2d/31408d2d.png",
  },
  {
    name: "Miles Morales",
    attack: 3,
    hp: 1,
    cost: 3,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/1a/ab/71/34/1aab7134.png",
  },
  {
    name: "Black Panther",
    attack: 4,
    hp: 3,
    cost: 3,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/39/4d/b0/52/394db052.png",
  },
  {
    name: "Captain America",
    attack: 1,
    hp: 2,
    cost: 1,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/63/48/f9/12/6348f912.png",
  },
  {
    name: "Black Widow",
    attack: 1,
    hp: 1,
    cost: 1,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/36/3b/e0/67/363be067.png",
  },
  {
    name: "Vision",
    attack: 4,
    hp: 2,
    cost: 3,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/cd/25/3c/c5/cd253cc5.png",
  },
  {
    name: "Quicksilver",
    attack: 2,
    hp: 2,
    cost: 2,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/37/7a/8e/4f/377a8e4f.png",
  },
  {
    name: "Black Cat",
    attack: 2,
    hp: 1,
    cost: 1,
    url: "https://hearthcards.ams3.digitaloceanspaces.com/e0/c9/9a/7a/e0c99a7a.png",
  },
];
